<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks></TargetFrameworks>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);CA1707;CA1822</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\LeanOAuth.Core\LeanOAuth.Core.csproj" />
    </ItemGroup>

</Project>
