<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
        <Title>LeanOAuth.Http</Title>
        <Description>HttpRequestMessage signing, the signing DelegatingHandler, and the three-legged flow for LeanOAuth, an open source implementation of the OAuth1.0A RFC 5849 protocol in .NET. Part of LeanOAuth project.</Description>
        <PackageTags>oauth,oauth1.0a,auth,dotnet,http</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LeanOAuth.Core\LeanOAuth.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNet.ReproducibleBuilds">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt" />
        <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
    </ItemGroup>

</Project>
