<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>LeanOAuth.AspNetCore</Title>
        <Description>ASP.NET Core sign-in handler and dependency injection extensions for LeanOAuth, an open source implementation of the OAuth1.0A RFC 5849 protocol in .NET. Part of LeanOAuth project.</Description>
        <PackageTags>oauth,oauth1.0a,auth,dotnet,aspnetcore</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LeanOAuth.Http\LeanOAuth.Http.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNet.ReproducibleBuilds">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.SourceLink.GitHub">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt" />
        <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
    </ItemGroup>

</Project>
